### ISSUE TITLE
[FR] Julia general registry

### ISSUE THREAD

**Issue by BambOoxX** [openturns/openturns.jl#1]
Hello !
Is there a plan to register `openturns.jl` in the julia general registry ?
This would surely lead to a better visibility of this package.

**Comment by jschueller** [comment]
hi, these bindings are not very advanced; you cant do much in the current state, so...

**Comment by BambOoxX** [comment]
Do you mean that there are no plans to develop those bindings further ?

**Comment by jschueller** [comment]
not in short-term at least, I was just being curious about julia
